# This is a config for E2B sandbox template.
# You can use template ID (tupl9qzzgmn0d2f4g7bs) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("tupl9qzzgmn0d2f4g7bs") # Sync sandbox
# sandbox = await AsyncSandbox.create("tupl9qzzgmn0d2f4g7bs") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('tupl9qzzgmn0d2f4g7bs')

dockerfile = "Dockerfile"
template_id = "tupl9qzzgmn0d2f4g7bs"
